[project]
name = "backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "asyncpg",
    "pydantic-settings",
    "python-dotenv",
    "passlib[bcrypt]",
    "email-validator"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"